# Default values for helm-personal-website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: joepoptiya/personal-website
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  host: "personal.127.0.0.1.nip.io"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
