apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personal-website.fullname" . }}
  labels:
    {{- include "personal-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "personal-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "personal-website.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "personal-website.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
