apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-website-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/joepoptiya/personal-website
    targetRevision: main
    path: helm-personal-website
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "image.tag"
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
