apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-website-helm
spec:
  project: default
  source:
    repoURL: https://github.com/joepoptiya/personal-website
    targetRevision: main
    path: helm-personal-website
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
